export const seedCategories = [
  {
    name: "Sarees",
    slug: "sarees",
    description: "Elegant ready-to-wear and traditional sarees",
    sort_order: 1,
  },
  {
    name: "T-Shirts",
    slug: "t-shirts",
    description: "Trendy graphic and plain tees for every style",
    sort_order: 2,
  },
  {
    name: "Jeans & Bottoms",
    slug: "jeans",
    description: "Cargo denim, joggers, and utility pants",
    sort_order: 3,
  },
  {
    name: "Ethnic Wear",
    slug: "ethnic-wear",
    description: "Jodhpuri sets and kurta collections",
    sort_order: 4,
  },
] as const;

export const seedProducts = [
  {
    category_slug: "sarees",
    name: "Magnetic Mint Ready-to-Wear Saree",
    slug: "magnetic-mint-ready-to-wear-saree",
    description:
      "Effortless drape with a magnetic mint finish for modern occasions.",
    price: 7500,
    compare_at_price: 15000,
    image_url:
      "https://images.unsplash.com/photo-1610030458921-c7ad1b99dd94?w=800&q=80",
    badge: "-50%",
    is_new_arrival: true,
    is_featured: false,
    is_popular: false,
  },
  {
    category_slug: "sarees",
    name: "Sassy Saffron Ready-to-Wear Saree",
    slug: "sassy-saffron-ready-to-wear-saree",
    description:
      "Bold saffron tones with a contemporary ready-to-wear silhouette.",
    price: 7500,
    compare_at_price: 15000,
    image_url:
      "https://images.unsplash.com/photo-1583391734526-7cdb30ee5ff5?w=800&q=80",
    badge: "-50%",
    is_new_arrival: true,
    is_featured: false,
    is_popular: false,
  },
  {
    category_slug: "sarees",
    name: "Offshore Ocean Ready-to-Wear Saree",
    slug: "offshore-ocean-ready-to-wear-saree",
    description: "Ocean-inspired hues with fluid, graceful draping.",
    price: 8000,
    compare_at_price: 12000,
    image_url:
      "https://images.unsplash.com/photo-1617627143750-d86bc21e3511?w=800&q=80",
    badge: "-33%",
    is_new_arrival: true,
    is_featured: true,
    is_popular: false,
  },
  {
    category_slug: "sarees",
    name: "The Queen's Lustrous Lime Saree",
    slug: "the-queens-lustrous-lime-saree",
    description: "A luminous lime saree crafted for statement evenings.",
    price: 5000,
    compare_at_price: 9800,
    image_url:
      "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80",
    badge: "-49%",
    is_new_arrival: true,
    is_featured: false,
    is_popular: false,
  },
  {
    category_slug: "sarees",
    name: "Noor-e-Hara Saree",
    slug: "noor-e-hara-saree",
    description: "Fresh green elegance with refined festive detailing.",
    price: 4000,
    compare_at_price: 5600,
    image_url:
      "https://images.unsplash.com/photo-1564557287817-3785e38c1b45?w=800&q=80",
    badge: "-29%",
    is_new_arrival: false,
    is_featured: false,
    is_popular: true,
  },
  {
    category_slug: "sarees",
    name: "Ruby Martini Cocktail Saree",
    slug: "ruby-martini-cocktail-saree",
    description: "Cocktail-ready glamour in rich ruby tones.",
    price: 4000,
    compare_at_price: 6500,
    image_url:
      "https://images.unsplash.com/photo-1583391734526-7cdb30ee5ff5?w=800&q=80",
    badge: "-38%",
    is_new_arrival: false,
    is_featured: false,
    is_popular: true,
  },
  {
    category_slug: "t-shirts",
    name: "Men's White Pop Hope Typography T-shirt",
    slug: "mens-white-pop-hope-typography-tshirt",
    description: "Clean white tee with bold hope typography.",
    price: 799,
    compare_at_price: null,
    image_url:
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80",
    badge: null,
    is_new_arrival: false,
    is_featured: true,
    is_popular: false,
  },
  {
    category_slug: "t-shirts",
    name: "Men's Black Vagabond Graphic Printed T-shirt",
    slug: "mens-black-vagabond-graphic-tshirt",
    description: "Street-ready black graphic tee with attitude.",
    price: 499,
    compare_at_price: null,
    image_url:
      "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800&q=80",
    badge: null,
    is_new_arrival: false,
    is_featured: false,
    is_popular: false,
  },
  {
    category_slug: "t-shirts",
    name: "Urban Mini Printed T-Shirt",
    slug: "urban-mini-printed-tshirt",
    description: "Compact urban print for everyday casual wear.",
    price: 999,
    compare_at_price: null,
    image_url:
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80",
    badge: null,
    is_new_arrival: false,
    is_featured: true,
    is_popular: false,
  },
  {
    category_slug: "t-shirts",
    name: "OtakuStorm Multi-Character Anime",
    slug: "otakustorm-multi-character-anime",
    description: "Anime-inspired oversized tee for otaku culture fans.",
    price: 899,
    compare_at_price: null,
    image_url:
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&q=80",
    badge: null,
    is_new_arrival: false,
    is_featured: false,
    is_popular: true,
  },
  {
    category_slug: "jeans",
    name: "Urban Rover Shadow Cargo Denim Jeans",
    slug: "urban-rover-shadow-cargo-denim-jeans",
    description: "Shadow-wash cargo denim with utility pockets.",
    price: 2199,
    compare_at_price: null,
    image_url:
      "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&q=80",
    badge: null,
    is_new_arrival: false,
    is_featured: true,
    is_popular: false,
  },
  {
    category_slug: "jeans",
    name: "Midnight Utility Black Cargo Denim Jeans",
    slug: "midnight-utility-black-cargo-denim-jeans",
    description: "All-black cargo denim built for urban exploration.",
    price: 1799,
    compare_at_price: null,
    image_url:
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80",
    badge: null,
    is_new_arrival: false,
    is_featured: true,
    is_popular: false,
  },
  {
    category_slug: "jeans",
    name: "Olive Utility Cargo Pants",
    slug: "olive-utility-cargo-pants",
    description: "Relaxed olive cargo pants with durable stitching.",
    price: 1099,
    compare_at_price: null,
    image_url:
      "https://images.unsplash.com/photo-1473966960800-7dee2ee2e7b0?w=800&q=80",
    badge: null,
    is_new_arrival: false,
    is_featured: false,
    is_popular: true,
  },
  {
    category_slug: "ethnic-wear",
    name: "Satya Light Pink Jodhpuri Set",
    slug: "satya-light-pink-jodhpuri-set",
    description: "Light pink jodhpuri set with short kurta and trouser.",
    price: 17260,
    compare_at_price: null,
    image_url:
      "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=800&q=80",
    badge: null,
    is_new_arrival: false,
    is_featured: true,
    is_popular: false,
  },
  {
    category_slug: "ethnic-wear",
    name: "Shaurya Multi Jodhpuri Set",
    slug: "shaurya-multi-jodhpuri-set",
    description:
      "Embroidered multi-tone jodhpuri set for festive occasions.",
    price: 15999,
    compare_at_price: null,
    image_url:
      "https://images.unsplash.com/photo-1596755094514-f87e34085b56?w=800&q=80",
    badge: null,
    is_new_arrival: false,
    is_featured: true,
    is_popular: false,
  },
] as const;
